name: Publish

on:
  workflow_call:
    inputs:
      tag_name:
        required: true
        type: string
      registry_fork:
        description: Registry fork to push to
        default: publish-to-bcr-dev/bazel-central-registry
        type: string
      registry:
        description: Override the registry to publish to
        default: publish-to-bcr-dev-registry/bazel-central-registry
        type: string
    secrets:
      BCR_PUBLISH_TOKEN:
        required: true

  # Manually trigger the publish workflow
  workflow_dispatch:
    inputs:
      tag_name:
        description: Release tag to publish to the Bazel Central Registry
        required: true
        type: string
      registry_fork:
        description: Registry fork to push to
        default: publish-to-bcr-dev/bazel-central-registry
        type: string
      registry:
        description: Override the registry to publish to
        default: publish-to-bcr-dev-registry/bazel-central-registry
        type: string

jobs:
  publish:
    uses: bazel-contrib/publish-to-bcr/.github/workflows/publish.yaml@fa2ae008c708886881d190bf6d3801b7e3345492
    with:
      tag_name: ${{ inputs.tag_name }}
      registry: ${{ inputs.registry }}
      registry_fork: ${{ inputs.registry_fork.registry_fork }}
      attest: true
      open_pull_request: false
    secrets:
      publish_token: ${{ secrets.BCR_PUBLISH_TOKEN }}
