name: Publish

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: Release tag to publish to the Bazel Central Registry
        required: true
        type: string
      registry_fork:
        description: Registry fork to push to
        required: true
        default: publish-to-bcr-dev/bazel-central-registry
        type: string  
      registry:
        description: Override the registry to publish to
        default: fweikert/bazel-central-registry
        type: string
      templates_ref:
        description: Override the ref to read .bcr templates from
        type: string

permissions:
  id-token: write
  attestations: write
  contents: write

jobs:
  publish:
    uses: publish-to-bcr-dev/.github/.github/workflows/publish.yaml@2bafafe2a9cfcaac330fa32553321f3e3a3d4874
    with:
      tag_name: ${{ inputs.tag_name }}
      registry: ${{ inputs.registry }}
      registry_fork: ${{ inputs.registry_fork }}
      templates_ref: ${{ inputs.templates_ref || inputs.tag_name }}
    secrets:
      publish_token: ${{ secrets.PUBLISH_TOKEN }}